### ISSUE TITLE
how will GST_REGISTRY variable work with both i686 and x86_64 registries?

### ISSUE THREAD

**Issue by jrobeson** [woegjiub/.config#1]
I found your dotfiles and just wondered if you had an idea on that. If nothing can really be done, then perhaps it should be annotated with a comment.

**Comment by woegjiub** [comment]
I believe that's only a legacy environment variable.

`http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstRegistry.html` states that the default is now `$XDG_CACHE_HOME/gstreamer-$GST_API_VERSION/registry-$ARCH.bin`, and the environment variable is `GST_REGISTRY`.

Are you seeing both versions on your system? If not, I'll probably remove that entry, as I believe I only had it back when firefox was using the older gstreamer version.

**Comment by jrobeson** [comment]
It's legacy in that gstreamer-0.1.x is legacy. It's not needed with gstreamer 1.x. 

There are still quite a popular programs built against gstreamer 0.1.x though. Some examples from my system:

* wine - ( at least in fedora packages)
* pidgin/libpurple
* firefox - official binaries (and maybe curent debian stable)
* banshee
* gajim 

You'd have to check your own distro to see if any of your own packages depend on gstreamer-0.10

**Comment by woegjiub** [comment]
It looks as though you'd have to export that in a shell command used as a launcher for your x86 applications before running them

As far as I'm aware, the only x86 software likely to be run in Linux is games, so having a wrapper may have to be something you'll have to do.

I'm fixing the value and adding a comment for now.
