### ISSUE TITLE
htop should no longer require this HOMERC

### ISSUE THREAD

**Issue by jrobeson** [woegjiub/.config#3]
`export HOMERC="$XDG_CONFIG_HOME/htop/htoprc"` in xdg.sh

You can see it here: http://man7.org/linux/man-pages/man1/htop.1.html

**Comment by woegjiub** [comment]
Unfortunately, a lot of the servers I log into are running older versions of GNU/Linux, so I need to keep it around for a while.

Thanks for the heads up though, it's good that they've converted, and are in addition using a different environment variable.
